### ISSUE TITLE
driver\i2c.h not found

### ISSUE THREAD

**Issue by techiesms** [m5stack/Applications-LidarBot#3]
I was trying to upload the code on my M5stack LIDAR bot but while compiling the Code I got this error. I search for this on Google but didn't find this file.

kindly guide me

**Comment by fsneew** [comment]
I'm having the same issue... Any idea ? 

Thanks

**Comment by TinyuZhao** [comment]
fix.https://github.com/m5stack/Applications-LidarBot/commit/6b57d5a1d3354843e1ebe31fa45557e4f8567758
